# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf93232df06617484f66dac5243b69ef438ba38049f589a5ebda56ee6b46d4b20824015d9ef67f777a8c0980cb1b0267af2fe39280c533984fec1b689eaa3851

test:
  secret_key_base: b479b74e5d1f9870b83dd7f32ced0706924010c1136b734d3dbc33e7d688268d7e548ab1461eba2bb7a260097b80ec09572d838558dea2b1f23b4b4c2ee83d25

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
